# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3da1364fbc6d0043cb9278a4708f8e070184076c680c4aeb3dbd3ee072f51f293d3bc9b340e3fb66e4c29161e567580800d60b3c95539b9bcc0757e927025fa

test:
  secret_key_base: d8be37d3543afc18b5ecba03748f33f1a33c12467cf9804c69257fc3bccf92410e942bfcd8acccecc2a39e3286a8fa37a53739823a224129a65053c24b28d4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
